### ISSUE TITLE
What does the "average accuracy with decay" mean when training the model?

### ISSUE THREAD

**Issue by BasselAli1** [ronghanghu/n2nmn#12]
`>  avg_accuracy += (1 - accuracy_decay) * (accuracy - avg_accuracy)`

I tired to google about "average accuracy" but I didn't find anything useful. 
Can anyone please tell me what this line is? and what is the "average accuracy"? Does it have multiple names in the literature because I did not find anything similar to it before?

**Comment by thaolmk54** [comment]
Did anybody figure this out? I found this being used throughout his projects but I have no clue where he got the idea from.
