### ISSUE TITLE
module missing

### ISSUE THREAD

**Issue by wlxhappiness** [ronghanghu/n2nmn#15]
Traceback (most recent call last):
  File "eval_clevr.py", line 22, in <module>
    from models_clevr.nmn3_assembler import Assembler
ModuleNotFoundError: No module named 'models_clevr'

**Comment by wlxhappiness** [comment]
when i run your test code on dataset-clever，there cause this error.
can you give me some solutions?thanks for much

**Comment by astha99** [comment]
Hi, were you able to figure out the error? I am stuck at the same step. Any help will be appreciated. Thank you.
