### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by goonmeet** [ronghanghu/n2nmn#17]
Hi!

It looks like the links to download the pre-trained models are broken (including VGG 16):

clevr_gt_layout (cloning expert): https://people.eecs.berkeley.edu/~ronghang/projects/n2nmn/models/clevr_gt_layout/
clevr_rl_gt_layout (policy search after cloning): https://people.eecs.berkeley.edu/~ronghang/projects/n2nmn/models/clevr_rl_gt_layout/
clevr_scratch (policy search from scratch): https://people.eecs.berkeley.edu/~ronghang/projects/n2nmn/models/clevr_scratch/

Thanks!

**Comment by ronghanghu** [comment]
Hi, sorry that the links have expired. I've uploaded them to Google Drive at https://drive.google.com/drive/folders/1-txrTE2RVbqnMqWYimZkb7UtVt_rr2dJ

**Comment by goonmeet** [comment]
Hello! 

Thank you so much for the quick action!
