### ISSUE TITLE
question about SHAPES data

### ISSUE THREAD

**Issue by rizar** [ronghanghu/n2nmn#6]
I am trying to understand the question number 5185 (in 0-based indexing) from the `train.large` subset of the SHAPES dataset. I visualize the image of the question by running 

```
import numpy
from matplotlib import pyplot

images = numpy.load('train.large.input.npy')
pyplot.imshow(images[5185])
pyplot.show()
```

and I see this:

![image](https://user-images.githubusercontent.com/654434/37610330-ad6f6e44-2b75-11e8-870f-719eed4ba415.png)

Then I look at the question, which is `(is blue triangle)` or `is blue shape a triangle` depending on which representation I look at, and the answer, which is `false`. There clearly is a blue triangle in the image though.

Can you please explain what I am doing wrong?

**Comment by ronghanghu** [comment]
Hi, Sorry for the confusion here. The images are ordered in BGR channels (instead of RGB) as is the default with OpenCV, so you should use `cv2.imshow` or `pyplot.imshow(images[5185, ..., ::-1])` to visualize it.

**Comment by rizar** [comment]
Huge thanks for your super-quick reply, that explains everything!
